services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wt24
    networks:
      - arm-mreza
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nodejs-app:
    image: nodejs-app:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "3000:3000"
    networks:
      - arm-mreza
    depends_on:
      - mysql
    command: ["wait-for-it", "mysql-db:3306", "--", "sh", "-c", "node initBazu.js && node index.js"]

networks:
  arm-mreza:
    driver: bridge
    name: arm-mreza

volumes:
  mysql-data:
