services:
  nodejs-app:
    image: scomor/arm-zadaca:nodejs-app
    container_name: nodejs-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
    networks:
      - arm-mreza
    restart: on-failure

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wt24
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - arm-mreza

networks:
  arm-mreza:
    driver: bridge
    name: arm-mreza

volumes:
  mysql-data: